template_path: "remote/cfn-tag-instance-policy.yaml"
stack_name: "cfn-tag-instance-policy"
dependencies:
  - "prod/bootstrap.yaml"
hooks:
  before_launch:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/cfn-tag-instance-policy.yaml --create-dirs -o templates/remote/cfn-tag-instance-policy.yaml"
