template_path: "remote/cfn-s3objects-macro.yaml"
stack_name: "cfn-s3objects-macro"
dependencies:
  - "prod/bootstrap.yaml"
hooks:
  before_create:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/cfn-s3objects-macro.yaml --create-dirs -o templates/remote/cfn-s3objects-macro.yaml"
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/cfn-s3objects-macro.yaml --create-dirs -o templates/remote/cfn-s3objects-macro.yaml"
