template_path: "remote/essentials.yaml"
stack_name: "essentials"
dependencies:
  - "prod/bootstrap.yaml"
parameters:
  OperatorEmail: "aws.scipooldev@sagebase.org"
  VpcPeeringRequesterAwsAccountId: "745159704268"
hooks:
  before_launch:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/essentials.yaml --create-dirs -o templates/remote/essentials.yaml"
