template_path: remote/peer-route-config.yaml
stack_name: peer-vpn-cesspoolvpc
dependencies:
  - prod/cesspoolvpc.yaml
parameters:
  PeeringConnectionId: "pcx-052484218893705d9"
  VpcPrivateRouteTable: "rtb-094f2336c06807361"
  VpcPublicRouteTable: "rtb-036d799b77abcd1fb"
  VpnCidr: "10.1.0.0/16"
hooks:
  before_create:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/peer-route-config.yaml --create-dirs -o templates/remote/peer-route-config.yaml"
  before_update:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/aws-infra/master/peer-route-config.yaml --create-dirs -o templates/remote/peer-route-config.yaml"
