template_path: "remote/sc-ec2-actions.yaml"
stack_name: "sc-ec2-actions"
dependencies:
  - "prod/sc-enduser-iam.yaml"
  - "prod/cfn-sc-actions-provider.yaml"
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
parameters:
  AssumeRole: "arn:aws:iam::465877038949:role/SCEC2LaunchRole"
hooks:
  before_launch:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/{{stack_group_config.service_catalog_library}}/master/ec2/sc-ec2-actions.yaml --create-dirs -o templates/remote/sc-ec2-actions.yaml"
