template_path: "remote/sc-tag-options.j2"
stack_name: "sc-tag-options"
stack_tags:
  Department: "Platform"
  Project: "Infrastructure"
  OwnerEmail: "it@sagebase.org"
dependencies:
  - "prod/sc-portfolio-ec2.yaml"
  - "prod/sc-portfolio-s3-basic.yaml"
sceptre_user_data:
  Departments:
    - "CompOnc"
    - "NDR"
    - "Platform"
    - "SysBio"
  Projects:
    - "amp-ad"
    - "challenge"  # Sometimes challenges aren't always DREAM
    - "csbs"
    - "dream"
    - "dream/metadata"
    - "genie"
    - "htan"
    - "iAtlas"
    - "Infrastructure"
    - "neurofibromatosis"
    - "pson"
  OwnerEmails:
    - "aaron.hayden@sagebase.org"
    - "anna.greenwood@sagebase.org"
    - "bruce.hoff@sagebase.org"
    - "cindy.molitor@sagebase.org"
    - "duminda.aluthgamage@sagebase.org"
    - "jake.gockley@sagebase.org"
    - "james.eddy@sagebase.org"
    - "joe.smith@sagebase.org"
    - "jineta.banerjee@sagebase.org"
    - "kelsey.montgomery@sagebase.org"
    - "kenneth.daily@sagebase.org"
    - "khai.do@sagbase.org"
    - "larsson.omberg@sagebase.org"
    - "lea.martin@sagebase.org"
    - "laura.heath@sagebase.org"
    - "marco.marasca@sagebase.org"
    - "milen.nikolov@sagebase.org"
    - "phil.snyder@sagebase.org"
    - "tess.thyer@sagebase.org"
    - "thomas.yu@sagebase.org"
    - "vanessa.barone@sagebase.org"
    - "william.poehlman@sagebase.org"
    - "xengie.doan@sagebase.org"
    - "xindi.guo@sagebase.org"
    - "verena.chung@sagebase.org"
  ProductIDs:
    - !stack_output_external sc-portfolio-ec2::SCEC2portfolioId
    - !stack_output_external sc-portfolio-s3-basic::SCS3portfolioId
hooks:
  before_launch:
    - !cmd "curl https://s3.amazonaws.com/{{stack_group_config.admincentral_cf_bucket}}/{{stack_group_config.service_catalog_library}}/master/common/sc-tag-options.j2 --create-dirs -o templates/remote/sc-tag-options.j2"
